apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose-windows-amd64.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: gate-service
  name: gate-service
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gate-service
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose-windows-amd64.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/temp-default: "true"
        io.kompose.service: gate-service
    spec:
      containers:
        - env:
            - name: MYSQL_DB_HOST
              value: mysql-gate
            - name: MYSQL_DB_PASSWORD
              value: abc123
            - name: MYSQL_DB_PORT
              value: "3306"
            - name: MYSQL_DB_USERNAME
              value: root
          image: putxander/gate-service
          name: gate-service
          ports:
            - containerPort: 8083
              hostPort: 8083
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
