apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  labels:
    name: prometheus-config-map
data:
  prometheus.rules:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'airport-service'
        metrics_path: '/actuator/prometheus'
        static_configs:
          - targets: 
            - airport-service:8081