apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config-map
  labels:
    name: prometheus-config-map
data:
  prometheus.rules:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s