name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  front-end:
    name: Deploy to Firebase Hosting
  runs-on: ubuntu-latest

  defaults:
    run:
      working-directory: ./frontend

  steps:
    - name: Check out repository
      uses: actions/checkout@v3

    - name: Install dependencies
    run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy to Firebase
    uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MICROSERVICES_EDE }}'
        channelId: live
        projectId: microservices-ede